linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/stretchr/testify/require
          - github.com/stretchr/testify/mock
          - github.com/PrusovaIU/otus_golang_homework/hw09_struct_validator