// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StringInterface is an autogenerated mock type for the StringInterface type
type StringInterface struct {
	mock.Mock
}

type StringInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StringInterface) EXPECT() *StringInterface_Expecter {
	return &StringInterface_Expecter{mock: &_m.Mock}
}

// String provides a mock function with given fields:
func (_m *StringInterface) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StringInterface_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type StringInterface_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *StringInterface_Expecter) String() *StringInterface_String_Call {
	return &StringInterface_String_Call{Call: _e.mock.On("String")}
}

func (_c *StringInterface_String_Call) Run(run func()) *StringInterface_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StringInterface_String_Call) Return(_a0 string) *StringInterface_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StringInterface_String_Call) RunAndReturn(run func() string) *StringInterface_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewStringInterface creates a new instance of StringInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStringInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StringInterface {
	mock := &StringInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
