linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/stretchr/testify/require
          - github.com/stretchr/testify/mock
          - github.com/schollz/progressbar/v3