// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileSeek is an autogenerated mock type for the FileSeek type
type FileSeek struct {
	mock.Mock
}

type FileSeek_Expecter struct {
	mock *mock.Mock
}

func (_m *FileSeek) EXPECT() *FileSeek_Expecter {
	return &FileSeek_Expecter{mock: &_m.Mock}
}

// Seek provides a mock function with given fields: _a0, _a1
func (_m *FileSeek) Seek(_a0 int64, _a1 int) (int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSeek_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type FileSeek_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - _a0 int64
//   - _a1 int
func (_e *FileSeek_Expecter) Seek(_a0 interface{}, _a1 interface{}) *FileSeek_Seek_Call {
	return &FileSeek_Seek_Call{Call: _e.mock.On("Seek", _a0, _a1)}
}

func (_c *FileSeek_Seek_Call) Run(run func(_a0 int64, _a1 int)) *FileSeek_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *FileSeek_Seek_Call) Return(_a0 int64, _a1 error) *FileSeek_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSeek_Seek_Call) RunAndReturn(run func(int64, int) (int64, error)) *FileSeek_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileSeek creates a new instance of FileSeek. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSeek(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSeek {
	mock := &FileSeek{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
